{ DIALECT: extended }
DEVICE INTERFACE;
UNIT REJECTDEVICEUNSAFE (touch);
TYPE Cells = SUPER ARRAY [2..*] OF INTEGER32; PCells = ^Cells;
PROCEDURE touch(p: PCells);
END;
DEVICE IMPLEMENTATION OF REJECTDEVICEUNSAFE;
PROCEDURE touch(p: PCells);
VAR raw: CPTR;
BEGIN raw := UNSAFERAW(p) END;
.
