{ DIALECT: extended }
PROGRAM HOSTDEVICEINTRINSICTYPES;
TYPE PINT = ^INTEGER32;
VAR p: PINT;
PROCEDURE kernel(data: PINT);
BEGIN END;
BEGIN
  p := DEVALLOC(TRUE);
  DEVCOPYTO(1, p, TRUE);
  DEVCOPYFROM(p, FALSE, 1);
  DEVFREE(1);
  LAUNCH(kernel, FALSE, 1, p)
END.
