DEVICE INTERFACE;
UNIT HOSTINTRINSICSINDEVICE (bad);
PROCEDURE bad;
END;
DEVICE IMPLEMENTATION OF HOSTINTRINSICSINDEVICE;
PROCEDURE bad;
TYPE PINT = ^INTEGER32;
VAR p: PINT;
BEGIN
  p := DEVALLOC(4);
  DEVCOPYTO(p, p, 4);
  DEVCOPYFROM(p, p, 4);
  DEVFREE(p);
  LAUNCH(bad, 1, 1)
END;
.
