{ DIALECT: extended }
PROGRAM DescriptorUnsafeShadow(output);
FUNCTION UNSAFERAW(n: INTEGER): INTEGER;
BEGIN UNSAFERAW := n + 1 END;
FUNCTION UNSAFESUPER(n: INTEGER): INTEGER;
BEGIN UNSAFESUPER := n + 2 END;
BEGIN WRITELN(UNSAFERAW(3), ' ', UNSAFESUPER(3)) END.
